# Generated by Django 3.2.25 on 2025-12-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий (при переводе в "принято в работу")'),
        ),
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='изображение дизайна (при переводе в  "Выполнено")'),
        ),
    ]
